"""Async repository interfaces consumed by product services."""

from __future__ import annotations

from typing import Protocol

from .records import (
    AgentDecisionRecord,
    ApprovalRecord,
    ClusterRecord,
    CredentialRecord,
    GuardianScoreRecord,
    JobRecord,
    LivePassRateRecord,
    ProvisionEventRecord,
    RoutingRecord,
    TrafficRequestRecord,
    TrafficAggregateRecord,
)


class TrafficStore(Protocol):
    async def append(self, record: TrafficRequestRecord) -> TrafficRequestRecord: ...
    async def list_for_prompt_hash(
        self, prompt_hash: str, *, limit: int = 1000
    ) -> list[TrafficRequestRecord]: ...
    async def count(self) -> int: ...
    async def summarize_by_prompt_hash(self) -> list[TrafficAggregateRecord]: ...


class ClusterStore(Protocol):
    async def put(self, record: ClusterRecord) -> ClusterRecord: ...
    async def get(self, cluster_id: str) -> ClusterRecord | None: ...
    async def list(self) -> list[ClusterRecord]: ...


class RoutingStore(Protocol):
    async def put(self, record: RoutingRecord) -> RoutingRecord: ...
    async def get(self, cluster_id: str) -> RoutingRecord | None: ...


class LivePassRateStore(Protocol):
    async def record_score(
        self, record: GuardianScoreRecord, *, rolling_window: int = 20
    ) -> LivePassRateRecord: ...
    async def list_points(self, cluster_id: str) -> list[LivePassRateRecord]: ...


class JobStore(Protocol):
    async def put(self, record: JobRecord) -> JobRecord: ...
    async def get(self, job_id: str) -> JobRecord | None: ...
    async def list(self) -> list[JobRecord]: ...


class AgentDecisionStore(Protocol):
    async def put(self, record: AgentDecisionRecord) -> AgentDecisionRecord: ...
    async def get(self, decision_id: str) -> AgentDecisionRecord | None: ...
    async def latest_for_cluster(
        self, cluster_id: str, evidence_fingerprint: str | None = None
    ) -> AgentDecisionRecord | None: ...


class CredentialStore(Protocol):
    async def put(self, record: CredentialRecord) -> CredentialRecord: ...
    async def get(self, credential_id: str) -> CredentialRecord | None: ...
    async def get_for_user_provider(
        self, user_id: str, provider: str
    ) -> CredentialRecord | None: ...


class ApprovalStore(Protocol):
    async def put(self, record: ApprovalRecord) -> ApprovalRecord: ...
    async def get(self, approval_id: str) -> ApprovalRecord | None: ...
    async def get_by_decision(self, decision_id: str) -> ApprovalRecord | None: ...
    async def bind_provision_handle(
        self, approval_id: str, provision_handle: str
    ) -> ApprovalRecord: ...


class ProvisionAuditStore(Protocol):
    async def append(self, record: ProvisionEventRecord) -> ProvisionEventRecord: ...
    async def list_for_approval(self, approval_id: str) -> list[ProvisionEventRecord]: ...
